create table ability_score (description varchar(255), entity_index varchar(255) not null, full_name varchar(255), name varchar(255), url varchar(255), primary key (entity_index)) engine=InnoDB;
create table ability_score_value (value integer not null, id bigint not null auto_increment, player_character_id bigint, ability_score_entity_index varchar(255), primary key (id)) engine=InnoDB;
create table alignment (id bigint not null auto_increment, entity_index varchar(255), name varchar(255), url varchar(255), primary key (id)) engine=InnoDB;
create table background (id bigint not null auto_increment, entity_index varchar(255), name varchar(255), url varchar(255), primary key (id)) engine=InnoDB;
create table character_class (id bigint not null auto_increment, primary key (id)) engine=InnoDB;
create table player_character (class_level integer not null, experience integer not null, alignment_id bigint, background_id bigint, character_class_id bigint, id bigint not null auto_increment, race_id bigint, sub_race_id bigint, name varchar(255), player_name varchar(255), primary key (id)) engine=InnoDB;
create table player_character_spells (player_character_id bigint not null, spells_id bigint not null) engine=InnoDB;
create table race (id bigint not null auto_increment, race_details_id bigint, entity_index varchar(255), name varchar(255), url varchar(255), primary key (id)) engine=InnoDB;
create table race_details (speed integer not null, id bigint not null auto_increment, entity_index varchar(255), name varchar(255), primary key (id)) engine=InnoDB;
create table spell (level integer not null, spell_details_id integer, id bigint not null auto_increment, entity_index varchar(255), name varchar(255), url varchar(255), primary key (id)) engine=InnoDB;
create table spell_details (id integer not null auto_increment, entity_index varchar(255), primary key (id)) engine=InnoDB;
create table sub_race (id bigint not null auto_increment, entity_index varchar(255), name varchar(255), url varchar(255), primary key (id)) engine=InnoDB;
alter table race add constraint UKtc0arfydnhcm0mji2a6p9nb90 unique (entity_index);
alter table race_details add constraint UKkp7qfwwsbx0u2oa62y5qh4ng5 unique (entity_index);
alter table spell add constraint UK2gf32iu7xrrct807h6ongsd6g unique (entity_index);
alter table spell_details add constraint UK3m7adhydxyrj1ier7iihlmy2o unique (entity_index);
alter table sub_race add constraint UKhom0ikd5nmcp8xeq2p7d8rdhr unique (entity_index);
alter table ability_score_value add constraint FKfgc3m0rp2d8006itui4bmlbqh foreign key (ability_score_entity_index) references ability_score (entity_index);
alter table ability_score_value add constraint FKayvidj0s0sbco0xu985rptskx foreign key (player_character_id) references player_character (id);
alter table player_character add constraint FKs0brww9ncr2tidkxf0rdcj4hi foreign key (alignment_id) references alignment (id);
alter table player_character add constraint FKd3i045gwtsayw8j8efdu7fqka foreign key (background_id) references background (id);
alter table player_character add constraint FKnh37lmrp33chyvdh42jrvltvn foreign key (character_class_id) references character_class (id);
alter table player_character add constraint FK4ippnwl1lbi78cm4jd4yk3y46 foreign key (race_id) references race (id);
alter table player_character add constraint FKe92jp6dxkymq89otsxfymkaod foreign key (sub_race_id) references sub_race (id);
alter table player_character_spells add constraint FKfy74hu74j6ngi0jcucy9don6k foreign key (spells_id) references spell (id);
alter table player_character_spells add constraint FKq383y8ms7eu9u8geske6abxvl foreign key (player_character_id) references player_character (id);
alter table race add constraint FK4oby53hukqadi8x6ciiuyvkqs foreign key (race_details_id) references race_details (id);
alter table spell add constraint FKk5bajc8j0gugqangl2roivvxb foreign key (spell_details_id) references spell_details (id);
